### ISSUE TITLE
The addImage does not support files of type 'UNKNOWN' error is thrown when the survey contains a specific image

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-pdf#183]
Original issue: [T11459 - Error Export PDF with Image](https://surveyjs.answerdesk.io/internal/ticket/details/T11459)
```
Uncaught Error: addImage does not support files of type 'UNKNOWN', please ensure that a plugin for 'UNKNOWN' support is added.
    at Object.P (addimage.js:860:13)
    at t.addImage (addimage.js:821:34)
    at DrillForContent (from_html.js:413:1)
    at from_html.js:709:1
    at done (from_html.js:561:1)
    at img.onerror.img.onload (from_html.js:587:1)
```

**Comment by JaneSjs** [comment]
The exception stack trace indicates that the exception occurs in a jspdf library unable to process the provided images. It appears that enabling the [applyImageFit](https://surveyjs.io/pdf-generator/documentation/api-reference/idocoptions#applyImageFit) option resolves the issue.
```
var options = {
    applyImageFit: true
}
const surveyPDF = new SurveyPDF.SurveyPDF(json, options);
```
The [updated sample](https://plnkr.co/edit/qhttp9ZLxFHZ87XM).
