### ISSUE TITLE
The Cannot read properties of null (reading 'width') exception occurs when exporting a survey with a File question which contains a GIF image

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-pdf#208]
Original issue: [T12466 - Save Completed Forms to PDF  - getting width error](https://surveyjs.answerdesk.io/internal/ticket/details/T12466)

To reproduce the issue, run [this example](https://codesandbox.io/s/surveyjs-library-vue-forked-1221hg?file=/src/components/SurveyPdfComponent.vue) and upload the attached GIF image to the File question.
The fillowing exception occurs:
```
flat_file.ts:50 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'width')
    at FlatFile.eval (flat_file.ts:50:76)
    at step (helpers.ts:83:23)
    at Object.eval [as next] (helpers.ts:64:63)
    at fulfilled (helpers.ts:54:63)
```

**Comment by JaneSjs** [comment]
It appears that the jspdf library (which is internally used by Survey PDF) doesn't support TIF images: https://github.com/parallax/jsPDF/issues/2303. Please consider converting images to another format, for example, `jpg` or `png`.
