### ISSUE TITLE
The 'Cannot set properties of null (setting 'rowTitleWidth')' exception occurs when exporting a Multiple-Choice Matrix

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-pdf#216]
I want to export a Multiple-Choice Matrix which defines a rowTitleWidth to be `80%`: [example](https://plnkr.co/edit/T2GCp5CExoBAcp36). The following exception occurs:
```
Uncaught TypeError: Cannot set properties of null (setting 'rowTitleWidth')
    at createSurveyPdfModel (<anonymous>:19:24)
    at saveSurveyToPdf (<anonymous>:33:3)
    at savePdf (<anonymous>:40:5)
    at Object.lj (react-dom.production.min.js:223:217)
    at kj (react-dom.production.min.js:34:117)
    at nj (react-dom.production.min.js:34:171)
    at gh (react-dom.production.min.js:62:93)
    at Xg (react-dom.production.min.js:63:1)
    at react-dom.production.min.js:72:332
    at Tf (react-dom.production.min.js:189:448)
```

**Comment by JaneSjs** [comment]
The example code has a typo. Correct the code to:
```
 let matrix = surveyPDF.getQuestionByName('question1');
```
https://plnkr.co/edit/XOMgth7jDbbhT8b6
