### ISSUE TITLE
Survey with an HTML question - TypeError: Cannot read properties of undefined (reading '1')

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-pdf#229]
Original issue: T12822 - PDF generation issues
https://surveyjs.answerdesk.io/internal/ticket/details/T12822

A survey contains an HTML question. Run the example from the original thread, scroll down to the bottom of a page and click Export.
The following exception appears in the console:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '1')
    at h.renderParagraph (survey.pdf.min.js:26:14820)
    at h.setBlockBoundary (survey.pdf.min.js:26:15592)
    at n (survey.pdf.min.js:26:6651)
    at n (survey.pdf.min.js:26:6612)
    at n (survey.pdf.min.js:26:6612)
    at survey.pdf.min.js:26:9132
    at i (survey.pdf.min.js:26:6756)
    at v (survey.pdf.min.js:26:7171)
    at b (survey.pdf.min.js:26:9063)
    at t.fromHTML (survey.pdf.min.js:26:16427)
```

**Comment by dk981234** [comment]
</br></br> tags are not supported by from_html method
