### ISSUE TITLE
The Cannot read properties of null (reading 'width') exception occurs on an attempt to export a File question with an image

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-pdf#244]
To reproduce the issue, run the sample from the following thread and click Complete: T13152 - Issue with Survey PDF Generator
https://surveyjs.answerdesk.io/internal/ticket/details/T13152.

The following error occurs when you try to export a survey.
```
ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of null (reading 'width')
TypeError: Cannot read properties of null (reading 'width')
    at FlatFile.eval (flat_file.ts:50:76)
    at step (helpers.ts:83:23)
    at Object.eval [as next] (helpers.ts:64:63)
    at fulfilled (helpers.ts:54:63)
    at _ZoneDelegate.invoke (zone.js:372:26)
    at Object.onInvoke (core.mjs:26380:33)
    at _ZoneDelegate.invoke (zone.js:371:52)
    at Zone.run (zone.js:134:43)
    at eval (zone.js:1275:36)
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26367:33)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at drainMicroTaskQueue (zone.js:585:35)
    at ZoneTask.invokeTask [as invoke] (zone.js:491:21)
    at invokeTask (zone.js:1661:18)
    at globalCallback (zone.js:1692:29)
    at Image.globalZoneAwareCallback (zone.js:1725:16)
    at resolvePromise (zone.js:1211:31)
    at eval (zone.js:1118:17)
    at eval (zone.js:1134:33)
    at rejected (helpers.ts:55:94)
    at _ZoneDelegate.invoke (zone.js:372:26)
    at Object.onInvoke (core.mjs:26380:33)
    at _ZoneDelegate.invoke (zone.js:371:52)
    at Zone.run (zone.js:134:43)
    at eval (zone.js:1275:36)
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26367:33)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at drainMicroTaskQueue (zone.js:585:35)
    at ZoneTask.invokeTask [as invoke] (zone.js:491:21)
    at invokeTask (zone.js:1661:18)
    at globalCallback (zone.js:1692:29)
```

**Comment by JaneSjs** [comment]
The exception occurred because a SurveyPDF cannot build a preview for an uploaded image. You can solve the error using the following options:
* Disable image preview for SurveyPDF.
Disable the [allowImagesPreview](https://surveyjs.io/form-library/documentation/api-reference/file-model#allowImagesPreview) option for a File question of a Survey PDF instance to disable an image preview in PDF. Now, the PDF document contains a link; the link should allow users to download an image.
```js
surveyPdf.getQuestionByName("question1").allowImagesPreview = false;
```
[https://codesandbox.io/s/surveyjs-angular-forked-fxthy0?file=/src/app/components/survey.component.ts](https://codesandbox.io/s/surveyjs-angular-forked-fxthy0?file=/src/app/components/survey.component.ts)
* To display an image preview in PDF, add the `onDownloadFile` callback for a Survey PDF instance:
```js
const onDownloadCallback = (sender, options) => {
      console.log("download", options.content);
      const fileObj = this.agreementFiles.find(
        (item) => item.key === options.content
      );
      if (fileObj) {
        options.callback("success", window.URL.createObjectURL(fileObj.file));
      } else {
        options.callback("error");
      }
};
survey.onDownloadFile.add(onDownloadCallback);
...
surveyPdf.onDownloadFile.add(onDownloadCallback);
surveyPdf.mergeData(survey.data);
...
```
[https://codesandbox.io/s/surveyjs-angular-forked-zljf0v?file=/src/app/components/survey.component.ts](https://codesandbox.io/s/surveyjs-angular-forked-zljf0v?file=/src/app/components/survey.component.ts)
