### ISSUE TITLE
The 'Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'render')' exception is thrown when running custom PDF brick rendering using the TextFieldBrick

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-pdf#310]
T17445 - textBrick.render() throws an error
https://surveyjs.answerdesk.io/internal/ticket/details/T17445
***
[View CodeSandbox](https://codesandbox.io/p/sandbox/surveyjs-angular-forked-qk6t6t?file=%2Fsrc%2Fapp%2Fcomponents%2Fpdf.component.ts%3A13%2C1)
The following exception is thrown when using a custom brick rendering:
```
index.js:27 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'render')
TypeError: Cannot read properties of undefined (reading 'render')
    at TextFieldBrick.eval (pdf_textfield.ts:64:34)
    at step (helpers.ts:83:23)
    at Object.eval [as next] (helpers.ts:64:63)
    at eval (helpers.ts:57:71)
    at new ZoneAwarePromise (zone.js:1429:21)
    at __awaiter (helpers.ts:53:12)
    at TextFieldBrick.renderReadOnly (pdf_textfield.ts:58:5)
 ...
```

**Comment by JaneSjs** [comment]
The updated code is available in the original support thread.
